ApiRestWebClient/Models/ViewModels/DevsViewModel.cs
namespace ApiRestWebClient.Models.ViewModels
{
    public class DevsViewModel
    {       
        public int Id { get; set; }
        public string Nome { get; set; }        
    }
}

ApiRestWebClient/Models/ViewModels/ErrorViewModel.cs
using System;

namespace ApiRestWebClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApiRestWebClient/Models/ViewModels/ProjetoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApiRestWebClient.Models.ViewModels
{
    public class ProjetoViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

ApiRestWebClient/Models/ViewModels/RankingViewModel.cs
namespace ApiRestWebClient.Models.ViewModels
{
    public class RankingViewModel
    {
        public string NomeDoDesenvolvedor { get; set; }
        public int PosicaoDoRanking { get; set; }
        public double MediaDeHoras { get; set; }
    }
}

ApiRestWebClient/Models/ViewModels/TokenViewModel.cs
namespace ApiRestWebClient.Models.ViewModels
{
    public class TokenViewModel
    {
        public string Token { get; set; }
        public string User { get; set; }
    }
}

ApiRestWebClient/Controllers/DevsController.cs
using ApiRestWebClient.Models.ViewModels;
using ApiRestWebClient.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApiRestWebClient.Controllers
{
    public class DevsController : Controller
    {
        public IActionResult Index()
        {
            var apiMethods = new ApiMethods();
            var devs = apiMethods.RetornaDevs();
            var retorno = devs.Select(x => new DevsViewModel()
            {
                Id = x.Id,
                Nome = x.Nome

            });

            return View(retorno);
        }
    }
}

ApiRestWebClient/Controllers/HomeController.cs
using ApiRestWebClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ApiRestWebClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
  
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApiRestWebClient/Controllers/ProjetoController.cs
using ApiRestWebClient.Models.ViewModels;
using ApiRestWebClient.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ApiRestWebClient.Controllers
{
    public class ProjetoController : Controller
    {
        public IActionResult Index()
        {
            var apiMethods = new ApiMethods();
            var projetos = apiMethods.RetornaProjetos();
            var retorno = projetos.Select(x => new ProjetoViewModel()
            {
                Id = x.Id,
                Nome = x.Nome

            });

            return View(retorno);
        }
    }
}

ApiRestWebClient/Controllers/RankingController.cs
using ApiRestWebClient.Models.ViewModels;
using ApiRestWebClient.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ApiRestWebClient.Controllers
{
    public class RankingController : Controller
    {
        public IActionResult Index()
        {
            var apiMethods = new ApiMethods();
            var ranking = apiMethods.RetornaRanking();
            var retorno = ranking.Select(x => new RankingViewModel()
            {
                NomeDoDesenvolvedor = x.NomeDoDesenvolvedor,
                PosicaoDoRanking = x.PosicaoDoRanking,
                MediaDeHoras = x.MediaDeHoras             
            });

            return View(retorno);
        }
    }
}

ApiRestWebClient/Controllers/TokenController.cs
using ApiRestWebClient.Models.ViewModels;
using ApiRestWebClient.Services;
using Microsoft.AspNetCore.Mvc;

namespace ApiRestWebClient.Controllers
{
    public class TokenController : Controller
    {
        public IActionResult Index()
        {
            var viewModel = new TokenViewModel();
            var apiMethods = new ApiMethods();
            var token = apiMethods.RetornaToken();
            viewModel.Token = token.Token;
            viewModel.User = token.User;
            
            return View(viewModel);
        }
    }
}

ApiRestWebClient/Views/Devs/Index.cshtml
@model IEnumerable<ApiRestWebClient.Models.ViewModels.DevsViewModel>

@{
    ViewData["Title"] = "DEVS";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-12">
        <table id="token" name="token" class="table table-responsive table-hover table-striped">

            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                    <th>@Html.DisplayNameFor(model => model.Nome)</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Nome</td>
                    </tr>
                }

            </tbody>

        </table>
    </div>
</div>

ApiRestWebClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Web Client for consuming API REST.</p>
</div>

ApiRestWebClient/Views/Projeto/Index.cshtml
@model IEnumerable<ApiRestWebClient.Models.ViewModels.ProjetoViewModel>

@{
    ViewData["Title"] = "Projetos";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-12">
        <table id="token" name="token" class="table table-responsive table-hover table-striped">

            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                    <th>@Html.DisplayNameFor(model => model.Nome)</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Nome</td>
                    </tr>
                }

            </tbody>

        </table>
    </div>
</div>

ApiRestWebClient/Views/Ranking/Index.cshtml
@model IEnumerable<ApiRestWebClient.Models.ViewModels.RankingViewModel>

@{
    ViewData["Title"] = "Projetos";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-12">
        <table id="token" name="token" class="table table-responsive table-hover table-striped">

            <thead>
                <tr>
                    <th>Posi&Ccedil;&atilde;o no Ranking</th>
                    <th>Nome do Desenvolvedor</th>
                    <th>M&eacute;dia de Horas</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.PosicaoDoRanking</td>
                    <td>@item.NomeDoDesenvolvedor</td>
                    <td>@item.MediaDeHoras</td>
                </tr>
                }

            </tbody>

        </table>
    </div>
</div>

ApiRestWebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiRestWebClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApiRestWebClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Token" asp-action="Index">Token</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Devs" asp-action="Index">Devs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projeto" asp-action="Index">Projetos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ranking" asp-action="Index">Ranking</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ApiRestWebClient
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ApiRestWebClient/Views/Token/Index.cshtml
@model ApiRestWebClient.Models.ViewModels.TokenViewModel

@{
    ViewData["Title"] = "TOKEN";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-12">
        <table id="token" name="token" class="table table-responsive table-hover table-striped">

            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.User)</th>
                    <th>@Html.DisplayNameFor(model => model.Token)</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>@Model.User</td>
                    <td><label>@Model.Token</label></td>
                </tr>
            </tbody>

        </table>
    </div>
</div>